services:

  backend:
    build:
      context: ./backend
    container_name: payarr-backend

    env_file:
      - .env

    volumes:
      - ./backend:/app

    ports:
      - "8000:8000"

    depends_on:
      - database

    restart: unless-stopped


  frontend:
    build:
      context: ./frontend

    container_name: payarr-frontend

    ports:
      - "5173:80"

    depends_on:
      - backend

    restart: unless-stopped

  database:
    image: postgres:16
    container_name: payarr-db

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./database:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    restart: unless-stopped
