services:
  backend:
    build:
      context: ./backend
    container_name: payarr-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: postgres:16
    container_name: payarr-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: payarr
      POSTGRES_USER: payarr
      POSTGRES_PASSWORD: payarrpassword
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"