"""add checkout url to payments

Revision ID: bbd6ff1f4f40
Revises: edc2f13a6f21
Create Date: 2026-07-23 14:43:56.425536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd6ff1f4f40'
down_revision: Union[str, Sequence[str], None] = 'edc2f13a6f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('checkout_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'checkout_url')
    # ### end Alembic commands ###
